# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(252, 524)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.lineEditServerIp = QtWidgets.QLineEdit(Dialog)
        self.lineEditServerIp.setGeometry(QtCore.QRect(20, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditServerIp.setFont(font)
        self.lineEditServerIp.setText("")
        self.lineEditServerIp.setObjectName("lineEditServerIp")
        self.lineEditServerPort = QtWidgets.QLineEdit(Dialog)
        self.lineEditServerPort.setGeometry(QtCore.QRect(20, 120, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditServerPort.setFont(font)
        self.lineEditServerPort.setText("")
        self.lineEditServerPort.setObjectName("lineEditServerPort")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 250, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBoxColorScheme = QtWidgets.QComboBox(Dialog)
        self.comboBoxColorScheme.setGeometry(QtCore.QRect(20, 280, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBoxColorScheme.setFont(font)
        self.comboBoxColorScheme.setObjectName("comboBoxColorScheme")
        self.comboBoxColorScheme.addItem("")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 320, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 350, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 380, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 410, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.checkBoxClientAutostart = QtWidgets.QCheckBox(Dialog)
        self.checkBoxClientAutostart.setGeometry(QtCore.QRect(200, 320, 20, 21))
        self.checkBoxClientAutostart.setText("")
        self.checkBoxClientAutostart.setObjectName("checkBoxClientAutostart")
        self.checkBoxServerAutostart = QtWidgets.QCheckBox(Dialog)
        self.checkBoxServerAutostart.setGeometry(QtCore.QRect(200, 350, 20, 21))
        self.checkBoxServerAutostart.setText("")
        self.checkBoxServerAutostart.setObjectName("checkBoxServerAutostart")
        self.checkBoxFileIntegrity = QtWidgets.QCheckBox(Dialog)
        self.checkBoxFileIntegrity.setGeometry(QtCore.QRect(200, 380, 20, 21))
        self.checkBoxFileIntegrity.setText("")
        self.checkBoxFileIntegrity.setObjectName("checkBoxFileIntegrity")
        self.checkBoxAllowCommands = QtWidgets.QCheckBox(Dialog)
        self.checkBoxAllowCommands.setGeometry(QtCore.QRect(200, 410, 20, 21))
        self.checkBoxAllowCommands.setText("")
        self.checkBoxAllowCommands.setObjectName("checkBoxAllowCommands")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 170, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEditServerTimeout = QtWidgets.QLineEdit(Dialog)
        self.lineEditServerTimeout.setGeometry(QtCore.QRect(20, 200, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditServerTimeout.setFont(font)
        self.lineEditServerTimeout.setText("")
        self.lineEditServerTimeout.setObjectName("lineEditServerTimeout")
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonCancel.setGeometry(QtCore.QRect(20, 480, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButtonCancel.setFont(font)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.pushButtonSave = QtWidgets.QPushButton(Dialog)
        self.pushButtonSave.setGeometry(QtCore.QRect(130, 480, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 440, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.checkBoxConnectionEncrypted = QtWidgets.QCheckBox(Dialog)
        self.checkBoxConnectionEncrypted.setGeometry(QtCore.QRect(200, 440, 20, 21))
        self.checkBoxConnectionEncrypted.setText("")
        self.checkBoxConnectionEncrypted.setObjectName("checkBoxConnectionEncrypted")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Server Ip"))
        self.label_2.setText(_translate("Dialog", "Server Port"))
        self.label_3.setText(_translate("Dialog", "Color Scheme"))
        self.comboBoxColorScheme.setItemText(0, _translate("Dialog", "Dark"))
        self.label_4.setText(_translate("Dialog", "Client Autostart"))
        self.label_5.setText(_translate("Dialog", "Server Autostart"))
        self.label_6.setText(_translate("Dialog", "Check file integrity"))
        self.label_7.setText(_translate("Dialog", "Allow for commands"))
        self.label_8.setText(_translate("Dialog", "Server Timeout (sec)"))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel"))
        self.pushButtonSave.setText(_translate("Dialog", "Save"))
        self.label_9.setText(_translate("Dialog", "Connection Encrypted"))



